version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ada-challenge
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - '5000:5000'
    environment:
      - POSTGRES_URL=postgres://root:example@postgres/ada-challenge

volumes:
  postgres-data:
